[theme]
primaryColor = "#8b5cf6"
backgroundColor = "#6366f1"
secondaryBackgroundColor = "#f3e8ff"
textColor = "#1f2937"
font = "sans serif"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false
